version: '3.3'
services:
  mongo_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      backend:
        aliases:
          - post_db
          - comment_db
  ui:
    build: ./ui
    image: ${USERNAME}/ui:1.0
    ports:
      - 9292:9292/tcp
    networks:
      - frontend
  post:
    build: ./post-py
    image: ${USERNAME}/post:1.0
    networks:
      - frontend
      - backend
  comment:
    build: ./comment
    image: ${USERNAME}/comment:1.0
    networks:
      - frontend
      - backend
volumes:
  post_db:

networks:
  backend:
    ipam:
      config:
        - subnet: 10.0.2.0/24
  frontend:
    ipam:
      config:
        - subnet: 10.0.1.0/24
