version: '3.3'
services:
  mongo_db:
    image: mongo:${MONGO_IMAGE_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      backend:
        aliases:
          - post_db
          - comment_db
  ui:
    build: ./ui
    image: ${USERNAME}/ui:${UI_IMAGE_VERSION}
    ports:
      - ${UI_PORT}:9292/tcp
    networks:
      - frontend
  post:
    build: ./post-py
    image: ${USERNAME}/post:${POST_IMAGE_VERSION}
    networks:
      - frontend
      - backend
  comment:
    build: ./comment
    image: ${USERNAME}/comment:${COMMENT_IMAGE_VERSION}
    networks:
      - frontend
      - backend
volumes:
  post_db:

networks:
  backend:
    ipam:
      config:
        - subnet: ${BACKEND_SUBNET}
  frontend:
    ipam:
      config:
        - subnet: ${FRONTEND_SUBNET}
