version: '3.3'
services:
  prometheus:
    image: ${USER_NAME}/prometheus:${PROMETHEUS_IMAGE_VERSION}
    ports:
      - '9090:9090'
    networks:
      - monitoring
    deploy:
      placement:
        constraints:
          - node.labels.prometheus == true
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 10s

  node-exporter:
    image: prom/node-exporter:v0.15.0
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - monitoring
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 10s

  mongodb-exporter:
    image: eses/mongodb_exporter
    environment:
      - MONGODB_URL=mongodb://mongodb_1:27017
    networks:
      - backend
      - monitoring
    deploy:
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 10s
  
  cadvisor:
    image: google/cadvisor:latest
    volumes:
      - '/:/rootfs:ro'
      - '/var/run:/var/run:rw'
      - '/sys:/sys:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
    ports:
      - '8080:8080'
    networks:
      - monitoring
    deploy:
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 10s

  grafana:
    image: grafana/grafana
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=secret
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    networks:
      - monitoring
    deploy:
      placement:
        constraints:
          - node.labels.prometheus == true
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 10s

  alertmanager:
    image: ${USER_NAME}/alertmanager
    command:
      - '-config.file=/etc/alertmanager/config.yml'
    ports:
      - 9093:9093
    networks:
      - monitoring
    deploy:
      placement:
        constraints:
          - node.labels.prometheus == true
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 10s
      resources:
        limits:
          cpus: '0.1'
          memory: 100M


volumes:
  mongo_db:
  grafana_data:


networks:
  backend:
    ipam:
      config:
        - subnet: ${BACKEND_SUBNET}
  frontend:
    ipam:
      config:
        - subnet: ${FRONTEND_SUBNET}
  monitoring:
    ipam:
      config:
        - subnet: ${MONITORING_SUBNET}
